baseURL = 'https://piljoong.dev/'
languageCode = 'en-us'
title = 'piljoong.dev'
theme = "LoveIt"

[params]
    ShowReadingTime = true
[params.author]
    name = "piljoong"
    email = "kpiljoong@gmail.com"
[params.page.share]
    enable = true
    Linkiedin = true
    Reddit = true
    Weibo = false
