baseURL = 'https://piljoong.dev/'
languageCode = 'en-us'
title = 'piljoong.dev'
theme = "LoveIt"

[params]
    ShowReadingTime = true
    title = "piljoong.dev"
    description = "piljoong's tech blog"
[params.header.title]
    logo = ""
    name = "piljoong.dev"
[params.home.profile]
    subtitle = ""
[params.author]
    name = "piljoong"
    email = "kpiljoong@gmail.com"
[params.page.share]
    enable = true
    Linkiedin = true
    Reddit = true
    Weibo = false
[params.footer]
    hugo = false
